### ISSUE TITLE
Can't change port

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#3]
I tried changing the port but I get this message:

Error: Property differ but is frozen on abc: port

Any reason why this is not allowed?

**Comment by fgeorges** [comment]
There are 2 frozen properties: the server type (HTTP, XDBC...) and its port.

For the type, it is forbidden by the Management API.  I think the reason why I froze the port was because it requires a restart, and wanted to make sure I handle it properly before allowing it.

Can you try and remove `.freeze()` in `src/properties.js` on line 510, and see if it works for your use case?

**Comment by fgeorges** [comment]
The port was frozen because it makes MarkLogic restart.

I have implemented waiting for MarkLogic when necessary, on a property change.  And I unfroze the property port.

This is available in 0.31.0, which has been published on NPM.  Can you update and try it, please?

**Comment by eurochriskelly** [comment]
This works now. Thanks!
