### ISSUE TITLE
Cannot setup project in existing project if folder already exists

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#9]
My existing folder has a 'src' folder. mlproj asks if I want to continue but fails anyway during the project creation step. This does not seem necessary since the src folder created is empty anyway.

Workaround: move src out of the way temporarily.

**Comment by fgeorges** [comment]
Fixed in the following commits altogether (not released yet):

- https://github.com/fgeorges/mlproj-core/commit/3ebac98b44ae531fa02badf8d223b17205ab7ac4
- https://github.com/fgeorges/mlproj-core/commit/912023bcf5dbcbd77ee6c6968e5301b815b6385d
- https://github.com/fgeorges/mlproj/commit/1e2d49cbd6c507dcb504a6259f19d0a5991a5964
